<ul>
	<li>
		<label>作品ID</label>
		<span>{{=it.opus_code}}</span>
	</li>
	<li>
		<label>作品名称</label>
		<span>{{=it.opus_name}}</span>
	</li>
	<li>
		<label>作品类型</label>
		<span>{{=it.opus_type}}</span>
	</li>
	<li>
		<label>作品登记号</label>
		<span>{{!it.name}}</span>
	</li>
	<li>
		<label>作品登机构</label>
		<span>{{!it.name}}</span>
	</li>
	<li>
		<label>作品登委托机构</label>
		<span>{{!it.name}}</span>
	</li>
	<li>
		<label>题材类型</label>
		<span>{{=it.theme_type}}</span>
	</li>
	<li>
		<label>作品时长</label>
		<span>{{=it.opus_duration}}</span>
	</li>
	<li>
		<label>发表时间</label>
		<span>{{=it.publish_date}}</span>
	</li>

	<li>
		<label>创作时间</label>
		<span>{{=it.indite_date}}</span>
	</li>
	<li>
		<label>收录专辑</label>
		<span>{{=it.embody_album}}</span>
	</li>
	<li>
		<label>词曲是否有原件</label>
		<span>{{=formatobligee_type(m.is_original)}}</span>
	</li>
	<li class="w100">
		<label>版本说明</label>
		<span>{{=it.version_explain}}</span>
	</li>
	<li class="w100">
		<label>作品简介</label>
		<span>{{=it.opus_briefing}}</span>
	</li>
</ul>